# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/portfolio',
                'doc_host': 'https://sangyu.github.io',
                'git_url': 'https://github.com/sangyu/portfolio',
                'lib_path': 'portfolio'},
  'syms': {'portfolio.core': {'portfolio.core.foo': ('core.html#foo', 'portfolio/core.py')}}}
